# add-highlighter global/ number-lines

# plug.kak installation
source "%val{config}/plugins/plug.kak/rc/plug.kak"
# Plugins
plug "andreyorst/smarttab.kak"
plug "stoand/kakoune-idris"
plug "nhey/kakoune-fsharp"
plug "KJ_Duncan/kakoune-kotlin.kak" domain "bitbucket.org"

set-option global tabstop 4

hook global WinCreate ^[^*]+$ %{editorconfig-load}
hook global WinSetOption .* expandtab

